In [1]:
import pandas as pd
import numpy as np
import datetime 
import pickle

In [2]:
df = pd.read_csv(r'./dataset/events.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2756101 entries, 0 to 2756100
Data columns (total 5 columns):
timestamp        int64
visitorid        int64
event            object
itemid           int64
transactionid    float64
dtypes: float64(1), int64(3), object(1)
memory usage: 105.1+ MB


In [3]:
df = df.sort_values(by='timestamp')
df['datetime'] = pd.to_datetime(df['timestamp'], unit='ms')
df['date'] = [(_).strftime('%Y-%m-%d') for _ in df['datetime']]

In [4]:
df.head()

timestamp  visitorid      event  itemid  transactionid  \
1462974  1430622004384     693516  addtocart  297662            NaN   
1464806  1430622011289     829044       view   60987            NaN   
1463000  1430622013048     652699       view  252860            NaN   
1465287  1430622024154    1125936       view   33661            NaN   
1462955  1430622026228     693516       view  297662            NaN   

                       datetime        date  
1462974 2015-05-03 03:00:04.384  2015-05-03  
1464806 2015-05-03 03:00:11.289  2015-05-03  
1463000 2015-05-03 03:00:13.048  2015-05-03  
1465287 2015-05-03 03:00:24.154  2015-05-03  
1462955 2015-05-03 03:00:26.228  2015-05-03

In [5]:
df.tail()

timestamp  visitorid event  itemid  transactionid  \
1461164  1442545164029     472345  view  301436            NaN   
1456543  1442545165499    1207677  view  310922            NaN   
1456783  1442545174109     255126  view   47467            NaN   
1454122  1442545181778     622226  view  345308            NaN   
1459312  1442545187788    1287495  view   98299            NaN   

                       datetime        date  
1461164 2015-09-18 02:59:24.029  2015-09-18  
1456543 2015-09-18 02:59:25.499  2015-09-18  
1456783 2015-09-18 02:59:34.109  2015-09-18  
1454122 2015-09-18 02:59:41.778  2015-09-18  
1459312 2015-09-18 02:59:47.788  2015-09-18

In [6]:
dataset = []

for name, group in df.groupby(['visitorid', 'date']):
    dataset.append(group['itemid'].values)

In [7]:
len(dataset)

1649534

In [8]:
dataset[:5]

[array([285930, 357564,  67045]),
 array([72028]),
 array([325215, 325215, 259884, 216305, 342816, 342816, 216305, 325215]),
 array([385090]),
 array([177677])]

In [9]:
with open('./dataset/kaggle_dataset.pkl', 'wb') as fout:
    pickle.dump(dataset, fout)